[tool.poetry]
name = "innohassle-musicroom"
version = "0.1.0"
description = ""
authors = ["Saveliy <s.lekhtin@innopolis.university>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.105.0"
uvicorn = "^0.24.0.post1"
pydantic = { version = "^2.4.2", extras = ["email"] }
sqlalchemy = "^2.0.23"
asyncpg = "^0.29.0"
cryptography = "^41.0.4"
pillow = "^10.0.1"
pyyaml = "^6.0.1"
alembic = "^1.13.0"
ruff = "^0.1.8"
authlib = "^1.3.0"
python-docx = "^1.1.0"

[tool.ruff]
line-length = 120
ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
