[tool.poetry]
name = "innohassle-musicroom"
version = "0.1.0"
description = ""
authors = ["Saveliy <s.lekhtin@innopolis.university>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"
colorlog = "^6.8.2"

[tool.poetry.group.api.dependencies]
fastapi = "^0.110.0"
uvicorn = "^0.27.1"
sqlalchemy = "^2.0.23"
asyncpg = "^0.29.0"
cryptography = "^42.0.5"
pillow = "^10.3.0"
alembic = "^1.13.0"
authlib = "^1.3.0"
python-docx = "^1.1.0"
icalendar = "^5.0.11"
pydantic = { version = "<2.6", extras = ["email"] } # TODO: Update when aiogram supports pydantic 2.6+
httpx = "^0.27.0"

[tool.poetry.group.bot.dependencies]
aiogram = "^3.4.1"
redis = "^5.0.3"
aiohttp = "^3.9.3"
aiogram-dialog = "^2.1.0"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
ruff = "^0.3.4"
pre-commit = "^3.6.2"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
